# Generated by Django 3.2.6 on 2021-08-27 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Account Name', max_length=10)),
                ('account_number', models.CharField(help_text='Enter AWS Account Number', max_length=10)),
                ('region', models.CharField(help_text='Enter AWS Region', max_length=10)),
                ('aws_access_key', models.CharField(help_text='Enter AWS Access Key', max_length=10)),
                ('aws_secret_key', models.CharField(help_text='Enter AWS Secret Key', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
