# Generated by Django 3.2.6 on 2021-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_aws_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='aws_access_key',
            field=models.CharField(help_text='Enter AWS Access Key', max_length=20),
        ),
        migrations.AlterField(
            model_name='aws',
            name='aws_secret_key',
            field=models.CharField(help_text='Enter AWS Secret Key', max_length=40),
        ),
    ]
