# Generated by Django 3.2.6 on 2021-08-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20210828_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='region',
            field=models.CharField(help_text='Enter AWS Region', max_length=16),
        ),
    ]
