# Generated by Django 3.2.6 on 2021-08-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20210830_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='instance_id',
            field=models.CharField(help_text='Instance Id', max_length=80),
        ),
    ]
