# Generated by Django 3.2.6 on 2021-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_cronjob_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='aws_name_start',
            field=models.CharField(default='aws', help_text='AWS Name for Cron Job', max_length=200),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='aws_name_stop',
            field=models.CharField(default='aws', help_text='AWS Name for Cron Job', max_length=200),
        ),
    ]
